commands:
  - power_set
  - volume_set
  - treble_set
  - bass_set

states:
  power:
    type: boolean
  volume:
    type: number
  treble:
    type: number
  bass:
    type: number

modules:
  - AltecLansing.controller:
      i2c: 1
  - input:
      mode: switch
      pin: "!17"
      set: power_set
  - output:
      pin: "16"
      state: power
  - api:
